Repository gdsc-konkuk/Plantory-Android, pull requests merged in 2024-02, with the labels that each got.

#27 [FEAT] 홈 / 서버 연결 및 기능 구현, 오류 수정
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/dto/request/RequestGetPlantDailyRecord.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/dto/response/ResponseGetAllPlantsDto.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/dto/response/ResponseGetPlantDailyRecord.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/dto/response/ResponseGetUser.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/interceptor/AuthInterceptor.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/repository/PlantRepositoryImpl.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/service/PlantService.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/source/PlantDataSource.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/di/RepositoryModule.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/di/ServiceModule.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/entity/Plant.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/entity/PlantDetail.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/entity/PlantDiaryRecord.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/repository/PlantRepository.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/MainActivity.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/MainViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/SplashActivity.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeAdapter.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/NotificationAdapter.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/DiaryFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/DiaryViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/util/binding/BindingAdapter.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/util/view/PopupMenu.kt
  app/src/main/res/drawable/ic_menu_upload.xml
  app/src/main/res/drawable/ic_plant_add.xml
  app/src/main/res/drawable/img_home_new.png
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_diary.xml
  app/src/main/res/layout/item_home_plant.xml
  app/src/main/res/layout/menu_home.xml
  app/src/main/res/values/strings.xml
Labels: feat, 혜선

#29 [FEAT] 식물등록 연결 및 기능 구현
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/dto/request/RequestPostRegisterPlantDto.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/repository/PlantRepositoryImpl.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/service/PlantService.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/source/PlantDataSource.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/entity/PlantRegsiterItem.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/repository/PlantRepository.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/util/multipart/ContentUriRequestBody.kt
Labels: feat, 수연

#31 [FEAT] 식물상세 연결 및 기능 구현
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/dto/request/RequestPostPlantHistoryDto.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/dto/response/ResponseGetPlantHistoriesDto.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/repository/PlantRepositoryImpl.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/service/PlantService.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/source/PlantDataSource.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/entity/Plant.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/entity/PlantDailyRecord.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/entity/PlantHistory.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/repository/PlantRepository.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeAdapter.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailAdapter.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/DiaryViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/UploadViewModel.kt
  app/src/main/res/drawable/ic_detail_is_watered.xml
  app/src/main/res/drawable/ic_detail_record.xml
  app/src/main/res/drawable/ic_detail_water.xml
  app/src/main/res/drawable/plant.jpg
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/item_detail_calendar.xml
  app/src/main/res/layout/item_home_plant.xml
  app/src/main/res/values/colors.xml
Labels: feat, 수연

#34 [ADD] FCM 알림 / 채널 설정 및 앱 아이콘 추가
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/service/PlantoryMessagingService.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/NotificationAdapter.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/NotificationFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/NotificationViewModel.kt
  app/src/main/res/drawable/ic_launcher.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/item_home_notification.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
Labels: add, 혜선

#33 [ADD] 기초 세팅 / CI 적용과 KtLint 추가
  .editorconfig
  .github/workflows/plantory_pr_checker.yml
  app/build.gradle.kts
  app/src/androidTest/java/kr/ac/konkuk/gdsc/plantory/ExampleInstrumentedTest.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/application/Application.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/dto/request/RequestGetPlantDailyRecord.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/dto/request/RequestPostRegisterPlantDto.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/dto/request/RequestPostRegisterUserDto.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/dto/response/ResponseGetAllPlantsDto.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/dto/response/ResponseGetPlantHistoriesDto.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/repository/DataStoreRepositoryImpl.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/repository/PlantRepositoryImpl.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/repository/UserRepositoryImpl.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/service/PlantService.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/service/PlantoryMessagingService.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/service/UserService.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/source/PlantDataSource.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/di/DataStoreModule.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/di/RepositoryModule.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/di/RetrofitModule.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/di/ServiceModule.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/entity/Plant.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/entity/PlantDailyRecord.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/entity/PlantDetail.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/entity/PlantDiaryRecord.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/entity/PlantHistory.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/entity/PlantRegisterItem.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/repository/DataStoreRepository.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/repository/PlantRepository.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/repository/UserRepository.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/MainActivity.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/MainViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/SplashActivity.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeAdapter.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/NotificationAdapter.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/NotificationFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/NotificationViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailAdapter.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/PlantActivity.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/DiaryFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/DiaryViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/UploadFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/UploadViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/util/activity/ActivityExt.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/util/binding/BindingAdapter.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/util/decoration/ViewPagerDecoration.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/util/multipart/ContentUriRequestBody.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/util/view/PopupMenu.kt
  app/src/test/java/kr/ac/konkuk/gdsc/plantory/ExampleUnitTest.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: add, 혜선

#37 [FEAT] 식물기록등록 연결 및 기능 구현
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/dto/request/RequestPostRecordDto.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/dto/response/ResponseGetAllPlantsDto.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/repository/PlantRepositoryImpl.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/service/PlantService.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/source/PlantDataSource.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/entity/Plant.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/entity/PlantHistory.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/entity/PlantRecord.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/repository/PlantRepository.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeAdapter.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/DiaryFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/DiaryViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/UploadFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/UploadViewModel.kt
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_upload.xml
  app/src/main/res/values/strings.xml
Labels: feat, 수연

#39 [FEAT] 식물삭제+식물종정보GET / 서버 통신 연결 및 기능 구현
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/dto/response/ResponseGetPlantInformationsDto.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/repository/PlantRepositoryImpl.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/service/PlantService.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/source/PlantDataSource.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/entity/PlantInformation.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/repository/PlantRepository.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailAdapter.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/util/view/PopupDeleteMenu.kt
  app/src/main/res/drawable/ic_detail_delete.xml
  app/src/main/res/drawable/oval_gray_100_fill.xml
  app/src/main/res/layout/menu_detail.xml
Labels: feat, 수연

#41 [FEAT] 홈 / swipe refresh 구현 + 식물 기록 / 서버 연결 및 기능 구현
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/dto/response/ResponseGetPlantDailyRecord.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/dto/response/ResponseGetPlantRecordDto.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/repository/PlantRepositoryImpl.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/service/PlantService.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/source/PlantDataSource.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/repository/PlantRepository.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailAdapter.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/DiaryFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/DiaryViewModel.kt
  app/src/main/res/layout/fragment_diary.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_plant.xml
  app/src/main/res/values/strings.xml
Labels: feat, 혜선

#44 [FIX] 홈 / 화면 중복으로 올라오는 듯한 문제 수정
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/SplashActivity.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/util/activity/ActivityExt.kt
  app/src/main/res/anim/slide_in_left.xml
  app/src/main/res/anim/slide_in_right.xml
  app/src/main/res/anim/slide_out_left.xml
  app/src/main/res/anim/slide_out_right.xml
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/themes.xml
Labels: fix, 혜선

#45 [FEAT] 전체 / 사용성 개선
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/DiaryFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/util/binding/BindingAdapter.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/util/date/DateUtil.kt
  app/src/main/res/drawable/ic_detail_delete.xml
  app/src/main/res/drawable/ic_detail_record_complete.xml
  app/src/main/res/drawable/img_home_add_new.xml
  app/src/main/res/layout/fragment_add_plant.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_diary.xml
  app/src/main/res/layout/fragment_upload.xml
  app/src/main/res/layout/item_home_plant.xml
  app/src/main/res/values/strings.xml
Labels: feat, 혜선, 수연

#46 [chore] 출시 / 버전 업데이트
  .github/workflows/plantory_release_tag_generator.yml
  app/build.gradle.kts
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailAdapter.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/util/binding/BindingAdapter.kt
  app/src/main/res/drawable/oval_gray_100_fill.xml
  app/src/main/res/layout/fragment_diary.xml
  app/src/main/res/layout/item_detail_calendar.xml
Labels: 혜선, 수연, chore

#47 [fix] Post 오류 수정
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/UploadFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/UploadViewModel.kt
Labels: fix, 수연

#49 [UI] 홈-탄소저감 화면 구현
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeViewModel.kt
  app/src/main/res/drawable/shape_gray_50_fill_15.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_plant.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: ui, 수연

#50 [FIX] 스플래쉬, 홈 / 화면 재생성 문제 해결
  app/build.gradle.kts
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/SplashActivity.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/themes.xml
Labels: fix, 혜선
