Repository gdsc-konkuk/Plantory-Android, pull requests merged in 2024-01, with the labels that each got.

#4 [ADD] 폰트, 컬러 추가
  app/src/main/res/font/plantory_pretendard_bold.xml
  app/src/main/res/font/plantory_pretendard_regular.xml
  app/src/main/res/font/plantory_pretendard_semibold.xml
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
  app/src/main/res/values/appearance.xml
  app/src/main/res/values/colors.xml
Labels: add, 혜선

#7 [UI] 홈 UI 구현
  app/build.gradle.kts
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/entity/Plant.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeAdapter.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/util/decoration/ViewPagerDecoration.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/util/view/PopupMenu.kt
  app/src/main/res/drawable/ic_home_add.xml
  app/src/main/res/drawable/ic_home_logo.xml
  app/src/main/res/drawable/ic_menu_add.xml
  app/src/main/res/drawable/ic_menu_upload.xml
  app/src/main/res/drawable/ic_plant_upload.xml
  app/src/main/res/drawable/icon_home_notification.xml
  app/src/main/res/drawable/img_plant_sample.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_plant.xml
  app/src/main/res/layout/menu_home.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ui, 혜선

#10 [UI] 식물등록 화면 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/UploadViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/util/view/PopupMenu.kt
  app/src/main/res/color/customtextinput.xml
  app/src/main/res/drawable/ic_addplant_back.xml
  app/src/main/res/drawable/ic_addplant_datepicker.xml
  app/src/main/res/drawable/ic_addplant_profile.xml
  app/src/main/res/drawable/shape_gray_200_fill_10.xml
  app/src/main/res/drawable/shape_mint_fill_10.xml
  app/src/main/res/layout/fragment_add_plant.xml
  app/src/main/res/layout/simple_dropdown_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: ui, 수연

#13 [UI] 식물 기록 UI 구현
  app/build.gradle.kts
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/entity/PlantDailyRecord.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/DiaryFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/DiaryViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/util/binding/BindingAdapter.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/util/view/PopupMenu.kt
  app/src/main/res/drawable/ic_diary_checked.xml
  app/src/main/res/drawable/ic_diary_unchecked.xml
  app/src/main/res/layout/fragment_diary.xml
  app/src/main/res/values/strings.xml
Labels: ui, 혜선

#14 [UI] 식물 기록 등록 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/UploadFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/UploadViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/util/binding/BindingAdapter.kt
  app/src/main/res/drawable/box_upload_profile.xml
  app/src/main/res/drawable/ic_upload_profile.xml
  app/src/main/res/layout/fragment_add_plant.xml
  app/src/main/res/layout/fragment_upload.xml
  app/src/main/res/layout/simple_dropdown_item.xml
  app/src/main/res/values/strings.xml
Labels: ui, 수연

#16 [UI] 식물 상세 UI 구현
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/entity/Plant.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/entity/PlantDailyRecord.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeAdapter.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailAdapter.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/DiaryViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/UploadFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/UploadViewModel.kt
  app/src/main/res/drawable/ic_detail_add.xml
  app/src/main/res/drawable/ic_detail_back.xml
  app/src/main/res/drawable/ic_detail_calendar_left.xml
  app/src/main/res/drawable/ic_detail_calendar_right.xml
  app/src/main/res/drawable/ic_detail_menu.xml
  app/src/main/res/drawable/ic_detail_repot.xml
  app/src/main/res/drawable/ic_detail_upload.xml
  app/src/main/res/drawable/ic_detail_water.xml
  app/src/main/res/drawable/shape_gray_50_fill_5.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_diary.xml
  app/src/main/res/layout/item_detail_calendar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: ui, 수연

#18 [FEAT] FCM 알림 / 데이터 스토어, FCM 디바이스 토큰 발급
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/application/Application.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/repository/DataStoreRepositoryImpl.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/service/PlantoryMessagingService.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/di/DataStoreModule.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/di/RepositoryModule.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/repository/DataStoreRepository.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/MainActivity.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/MainViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/NotificationViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/DiaryViewModel.kt
  gradle/libs.versions.toml
Labels: feat, 혜선

#20 [UI] 스플래쉬 / 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/SplashActivity.kt
  app/src/main/res/drawable/ic_splash_logo.xml
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/themes.xml
Labels: ui, 혜선

#23 [UI] 식물 등록, 식물 기록 등록, 상세화면 수정사항 반영
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/entity/PlantInfo.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailAdapter.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailViewModel.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/DiaryFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/UploadFragment.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/diary/UploadViewModel.kt
  app/src/main/res/drawable/ic_detail_is_watered.xml
  app/src/main/res/drawable/ic_detail_not_watered.xml
  app/src/main/res/drawable/ic_detail_water.xml
  app/src/main/res/drawable/shape_gray_100_stroke_5.xml
  app/src/main/res/drawable/shape_watered_10_fill.xml
  app/src/main/res/layout/fragment_add_plant.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_upload.xml
  app/src/main/res/layout/item_detail_calendar.xml
  app/src/main/res/values/colors.xml
Labels: ui, 수연

#26 [FEAT] 회원 가입 / 디바이스 토큰 유저 등록
  app/build.gradle.kts
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/dto/request/RequestGetUser.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/dto/request/RequestPostRegisterUserDto.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/interceptor/AuthInterceptor.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/repository/UserRepositoryImpl.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/service/UserService.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/source/UserDataSource.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/di/RetrofitModule.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/repository/UserRepository.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/MainActivity.kt
  app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/MainViewModel.kt
Labels: feat, 혜선
